name: fogos
repository: https://github.com/FogosPT/fogospt.git 

packages:
  - apps/*
  - packages/*

ide:
  intellij:
    enabled: false

command:
  bootstrap:
    environment:
      sdk: '^3.3.0'
      flutter: '>=2.17.0 <3.0.0'
    dependencies:
      equatable: ^2.0.2
      freezed: ^2.4.7
      sentry: ^7.18.0
      http: ^1.2.1
      flutter_bloc: ^8.1.6
      flutter_map: ^7.0.2
      latlong2: ^0.9.1
      responsive_framework: ^1.4.0
      get_it: ^7.7.0



    dev_dependencies:
      build_runner: ^2.1.2
      bloc_test: ^9.1.6
      json_serializable: ^6.7.1
      flutter_lints: ^3.0.1
      mockito: ^5.4.4

    hooks:
      post: dart pub run build_runner build
      
      
  version:
    branch: vega


scripts: 
  analyze:
    exec: dart analyze .
  # fix:
  #   exec: dart fix . && dcm fix .

  build:
    exec: dart run build_runner build -d
    description: Run build runner on the projects
    packageFilters:
      dependsOn: build_runner