// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANwwPaUg0VpCyqZ3mESnBys-V6YPh5YlE',
    appId: '1:970378987492:web:77a1c6f0eba532b208a9f1',
    messagingSenderId: '970378987492',
    projectId: 'fogospt-dev',
    authDomain: 'fogospt-dev.firebaseapp.com',
    storageBucket: 'fogospt-dev.appspot.com',
    measurementId: 'G-186HYM3CHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA-Eyn8CsEyuacO6N86KdEcoxdoGqvzO0',
    appId: '1:970378987492:android:0b74831f0ebfb72108a9f1',
    messagingSenderId: '970378987492',
    projectId: 'fogospt-dev',
    storageBucket: 'fogospt-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMiHshyQni5apBe3PpspVnaBQ2JHi8iDg',
    appId: '1:970378987492:ios:1f54af5bc0d1c05808a9f1',
    messagingSenderId: '970378987492',
    projectId: 'fogospt-dev',
    storageBucket: 'fogospt-dev.appspot.com',
    iosBundleId: 'com.example.fogospt',
  );
}
