// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'fire.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$FireImpl _$$FireImplFromJson(Map<String, dynamic> json) => _$FireImpl(
      id: Id.fromJson(json['id'] as Map<String, dynamic>),
      datumId: json['datumId'] as String,
      coords: json['coords'] as bool,
      dateTime: Created.fromJson(json['dateTime'] as Map<String, dynamic>),
      date: json['date'] as String,
      hour: json['hour'] as String,
      location: json['location'] as String,
      aerial: (json['aerial'] as num).toInt(),
      meiosAquaticos: (json['meiosAquaticos'] as num).toInt(),
      man: (json['man'] as num).toInt(),
      terrain: (json['terrain'] as num).toInt(),
      district: json['district'] as String,
      concelho: json['concelho'] as String,
      freguesia: json['freguesia'] as String,
      dico: json['dico'] as String,
      lat: (json['lat'] as num).toDouble(),
      lng: (json['lng'] as num).toDouble(),
      naturezaCode: json['naturezaCode'] as String,
      natureza: json['natureza'] as String,
      especieName: json['especieName'],
      familiaName: json['familiaName'],
      statusCode: (json['statusCode'] as num).toInt(),
      statusColor: json['statusColor'] as String,
      status: json['status'] as String,
      important: json['important'] as bool,
      localidade: json['localidade'] as String,
      active: json['active'] as bool,
      sadoId: json['sadoId'] as String,
      sharepointId: (json['sharepointId'] as num).toInt(),
      extra: json['extra'],
      disappear: json['disappear'] as bool,
      icnf: json['icnf'] == null
          ? null
          : Icnf.fromJson(json['icnf'] as Map<String, dynamic>),
      detailLocation: json['detailLocation'] as String?,
      kml: json['kml'],
      kmlVost: json['kmlVost'],
      pco: json['pco'],
      cos: json['cos'],
      heliFight: (json['heliFight'] as num).toInt(),
      heliCoord: (json['heliCoord'] as num).toInt(),
      planeFight: (json['planeFight'] as num).toInt(),
      anepcDirectUpdate: json['anepcDirectUpdate'] as bool,
      regiao: json['regiao'] as String,
      subRegiao: json['subRegiao'] as String,
      created: Created.fromJson(json['created'] as Map<String, dynamic>),
      updated: Created.fromJson(json['updated'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$FireImplToJson(_$FireImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'datumId': instance.datumId,
      'coords': instance.coords,
      'dateTime': instance.dateTime,
      'date': instance.date,
      'hour': instance.hour,
      'location': instance.location,
      'aerial': instance.aerial,
      'meiosAquaticos': instance.meiosAquaticos,
      'man': instance.man,
      'terrain': instance.terrain,
      'district': instance.district,
      'concelho': instance.concelho,
      'freguesia': instance.freguesia,
      'dico': instance.dico,
      'lat': instance.lat,
      'lng': instance.lng,
      'naturezaCode': instance.naturezaCode,
      'natureza': instance.natureza,
      'especieName': instance.especieName,
      'familiaName': instance.familiaName,
      'statusCode': instance.statusCode,
      'statusColor': instance.statusColor,
      'status': instance.status,
      'important': instance.important,
      'localidade': instance.localidade,
      'active': instance.active,
      'sadoId': instance.sadoId,
      'sharepointId': instance.sharepointId,
      'extra': instance.extra,
      'disappear': instance.disappear,
      'icnf': instance.icnf,
      'detailLocation': instance.detailLocation,
      'kml': instance.kml,
      'kmlVost': instance.kmlVost,
      'pco': instance.pco,
      'cos': instance.cos,
      'heliFight': instance.heliFight,
      'heliCoord': instance.heliCoord,
      'planeFight': instance.planeFight,
      'anepcDirectUpdate': instance.anepcDirectUpdate,
      'regiao': instance.regiao,
      'subRegiao': instance.subRegiao,
      'created': instance.created,
      'updated': instance.updated,
    };
